# Form implementation generated from reading ui file 'c:\Users\provj709\Documents\ResearchandDevelopment\Routine-Walkthrough\routine-walkthrough\routine_walkthrough\routine_select.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

import json
from PyQt6.QtCore import QSize, Qt
from PyQt6.QtGui import QAction, QIcon
from PyQt6.QtGui import QFont, QFontDatabase
from PyQt6.QtWidgets import (
    QApplication,
    QCheckBox,
    QLabel,
    QMainWindow,
    QStatusBar,
    QToolBar,
    QPushButton,
)

from PyQt6 import QtCore, QtGui, QtWidgets

from routine_viewer_ui import Ui_RoutineViewer as urv

class Ui_RoutineSelect(QMainWindow):
    def __init__(self):
        super().__init__()
        self.r = ["place_holder", "another_place_holder"]
        self.w = None
        self.setObjectName("RoutineSelect")
        self.resize(400, 200)
        self.centralwidget = QtWidgets.QWidget(parent=self)
        self.centralwidget.setObjectName("centralwidget")
        self.instruction_select_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.instruction_select_text.setGeometry(QtCore.QRect(0, 0, 261, 151))
        self.instruction_select_text.setWordWrap(True)
        self.instruction_select_text.setFont(QFont("Calibri", 12))
        self.instruction_select_text.setObjectName("instruction_select_text")
        self.setCentralWidget(self.instruction_select_text)
        toolbar = QToolBar("THE toolbar")
        self.addToolBar(toolbar)
        menuplace_holder_1 = QAction("Morning", self)
        menuplace_holder_1.setObjectName("Morning")
        menuplace_holder_1.triggered.connect(self.open_first)
        menuplace_holder_1.setFont(QFont("Calibri", 11))
        toolbar.addAction(menuplace_holder_1)
        menuplace_holder_2 = QAction("Bedtime", self)
        menuplace_holder_2.setObjectName("Bedtime")
        menuplace_holder_2.triggered.connect(self.open_second)
        menuplace_holder_2.setFont(QFont("Calibri", 11))
        toolbar.addAction(menuplace_holder_2)
        menuplace_holder_3 = QAction("Fried Rice", self)
        menuplace_holder_3.setObjectName("Fried Rice")
        menuplace_holder_3.triggered.connect(self.open_third)
        menuplace_holder_3.setFont(QFont("Calibri", 11))
        toolbar.addAction(menuplace_holder_3)
        menuplace_holder_4 = QAction("Placeholder", self)
        menuplace_holder_4.setObjectName("Placeholder")
        menuplace_holder_4.triggered.connect(self.open_fourth)
        menuplace_holder_4.setFont(QFont("Calibri", 11))
        toolbar.addAction(menuplace_holder_4)
        menuplace_holder_5 = QAction("Present", self)
        menuplace_holder_5.setObjectName("Present")
        menuplace_holder_5.triggered.connect(self.open_fifth)
        menuplace_holder_5.setFont(QFont("Calibri", 11))
        toolbar.addAction(menuplace_holder_5)
        
        self.retranslateUi(self)
        
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, RoutineSelect):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("RoutineSelect", "RoutineSelect"))
        self.instruction_select_text.setText(_translate("RoutineSelect", "Choose which routine to walkthrough from the toolbar. Leaving the top text box with 'delete' will remove that item in the routine. You must press the next button and end button(end button not needed until you are finished) to save your edits."))
        
    def open_first(self):# try to come up with a different solution if possible
        self.open_viewer(1)

    def open_second(self):
        self.open_viewer(2)

    def open_third(self):
        self.open_viewer(3)

    def open_fourth(self):
        self.open_viewer(4)

    def open_fifth(self):
        self.open_viewer(5)
    
    def open_viewer(self, v = 0):
        print("here")
        print(str(v))
        v = v - 1
        print("open viewer")
        self.w = urv(v)
        self.w.show()
            
def startUp():
    routine = ["place_holder", "another_place_holder"]
    app1 = QApplication(sys.argv)

    stylesheet = None
    styles_path = "routine_walkthrough/styles.qss"
    with open(styles_path, "r") as f:
        stylesheet = f.read()
    app1.setStyleSheet(stylesheet)

    app1.setStyle("Fusion")
    w = Ui_RoutineSelect()
    w.show()
    app1.exec()
